season:
  number: 15
  finalised: 0
  formUrl: "WIP"
  blessingsDoc: "https://docs.google.com/document/d/18A6qsmrR8NgmqZ2mTTPre9QAPiyVvhAvyK0liKa5j80/edit"

documents:
  strategy: "https://docs.google.com/document/d/e/2PACX-1vTeyknT3OIEBEDvNKT8P5Km58y-7P3mEq2-mtC3rn3uqVvmAxiUV1uQyKgt71-Luj5Ux5vOmT5jLQga/pub"
  stadium: "https://docs.google.com/document/d/e/2PACX-1vQtchnE5O62EXEl3Qa2kFnKUJ8ZuB8Z1F6EwJoCfRG4KiPdfstaZ16gXdMPO0l6aEchRSljytM96gHm/pub"
art:
  logoCredit: "ZweiHawke#0173"
  logoUrl: "assets/img/logo.png"
  logoAltText: "A logo for the Core Mechanics. It has the text 'Core Mechanics' in white, over a teal spanner and a copper gear. A pale yellow subtitle reads 'THE CORE IS DOWN_', in the style of a computer terminal."