season:
  number: 14
  finalised: 1
  formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfmedBG5nOC-JQewwirlR77ivAWw88zfmXCPNBbEWrsbmlAUg/viewform"

documents:
  strategy: "https://docs.google.com/document/d/e/2PACX-1vTeyknT3OIEBEDvNKT8P5Km58y-7P3mEq2-mtC3rn3uqVvmAxiUV1uQyKgt71-Luj5Ux5vOmT5jLQga/pub"

art:
  logoCredit: "ZweiHawke#0173"
  logoUrl: "assets/img/logo.png"
  logoAltText: "A logo for the Core Mechanics. It has the text 'Core Mechanics' in white, over a teal spanner and a copper gear. A pale yellow subtitle reads 'THE CORE IS DOWN_', in the style of a computer terminal."