season:
  number: 17
  finalised: 1
  displayTargetMods: 0
  blessingWeighting: 4
  willWeighting: 6
  blessingsDoc: "https://docs.google.com/spreadsheets/d/1vuqvY6qQAP0PwWaNikr-4I4kpcA8ll7LxhbYxg0mRzA/edit?usp=sharing"
  strategyFormUrl: "https://forms.gle/5KXNV1sa992YrGiT6"
  formUrl: "https://forms.gle/7Mwtgm1p8QZNs3sCA"
  strategyPollUrl: https://forms.gle/jbUJ3SsKQkXrDS3ZA
documents:
  strategy: "https://docs.google.com/document/d/e/2PACX-1vTeyknT3OIEBEDvNKT8P5Km58y-7P3mEq2-mtC3rn3uqVvmAxiUV1uQyKgt71-Luj5Ux5vOmT5jLQga/pub"
  stadium: "https://docs.google.com/document/d/e/2PACX-1vQtchnE5O62EXEl3Qa2kFnKUJ8ZuB8Z1F6EwJoCfRG4KiPdfstaZ16gXdMPO0l6aEchRSljytM96gHm/pub"
art:
  logoCredit: "ZweiHawke#0173"
  logoUrl: "assets/img/logo.png"
  logoAltText: "A logo for the Core Mechanics. It has the text 'Core Mechanics' in white, over a teal spanner and a copper gear. A pale yellow subtitle reads 'THE CORE IS DOWN_', in the style of a computer terminal."